"""Add Phase 1 schema elements

Revision ID: c9a124acdc43
Revises: b3276c1c29e1
Create Date: 2026-08-30 15:58:05.792388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9a124acdc43'
down_revision: Union[str, Sequence[str], None] = 'b3276c1c29e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_detection_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scene_before_id', sa.BigInteger(), nullable=False),
    sa.Column('scene_after_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('result_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_asset_id'], ['sar_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_after_id'], ['sar_scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_before_id'], ['sar_scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_detection_jobs_id'), 'change_detection_jobs', ['id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['change_detection_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.add_column('sar_assets', sa.Column('scene_id', sa.BigInteger(), nullable=True))
    op.add_column('sar_assets', sa.Column('asset_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_sar_assets_id'), 'sar_assets', ['id'], unique=False)
    op.create_unique_constraint('uq_sar_asset_scene_key', 'sar_assets', ['scene_id', 'asset_key'])
    op.create_foreign_key(None, 'sar_assets', 'sar_scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    op.add_column('sar_requests', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_sar_requests_id'), 'sar_requests', ['id'], unique=False)
    op.add_column('sar_scenes', sa.Column('has_georeference', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_sar_scenes_id'), 'sar_scenes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sar_scenes_id'), table_name='sar_scenes')
    op.drop_column('sar_scenes', 'has_georeference')
    op.drop_index(op.f('ix_sar_requests_id'), table_name='sar_requests')
    op.drop_column('sar_requests', 'error_message')
    op.drop_constraint(None, 'sar_assets', type_='foreignkey')
    op.drop_constraint('uq_sar_asset_scene_key', 'sar_assets', type_='unique')
    op.drop_index(op.f('ix_sar_assets_id'), table_name='sar_assets')
    op.drop_column('sar_assets', 'asset_key')
    op.drop_column('sar_assets', 'scene_id')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_change_detection_jobs_id'), table_name='change_detection_jobs')
    op.drop_table('change_detection_jobs')
    # ### end Alembic commands ###
